Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds['twt'].plot()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mds[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mtwt[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/xarray/plot/plot.py:866[0m, in [0;36m_PlotMethods.__call__[0;34m(self, **kwargs)[0m
[1;32m    865[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m--> 866[0m     [38;5;28;01mreturn[39;00m [43mplot[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_da[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/xarray/plot/plot.py:332[0m, in [0;36mplot[0;34m(darray, row, col, col_wrap, ax, hue, rtol, subplot_kws, **kwargs)[0m
[1;32m    328[0m     plotfunc [38;5;241m=[39m hist
[1;32m    330[0m kwargs[[38;5;124m"[39m[38;5;124max[39m[38;5;124m"[39m] [38;5;241m=[39m ax
[0;32m--> 332[0m [38;5;28;01mreturn[39;00m [43mplotfunc[49m[43m([49m[43mdarray[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/xarray/plot/plot.py:1114[0m, in [0;36m_plot2d.<locals>.newplotfunc[0;34m(darray, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, center, robust, extend, levels, infer_intervals, colors, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)[0m
[1;32m   1111[0m     allargs[[38;5;124m"[39m[38;5;124mplotfunc[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mglobals[39m()[plotfunc[38;5;241m.[39m[38;5;18m__name__[39m]
[1;32m   1112[0m     [38;5;28;01mreturn[39;00m _easy_facetgrid(darray, kind[38;5;241m=[39m[38;5;124m"[39m[38;5;124mdataarray[39m[38;5;124m"[39m, [38;5;241m*[39m[38;5;241m*[39mallargs)
[0;32m-> 1114[0m plt [38;5;241m=[39m [43mimport_matplotlib_pyplot[49m[43m([49m[43m)[49m
[1;32m   1116[0m [38;5;28;01mif[39;00m (
[1;32m   1117[0m     plotfunc[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m"[39m[38;5;124msurface[39m[38;5;124m"[39m
[1;32m   1118[0m     [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124m_is_facetgrid[39m[38;5;124m"[39m, [38;5;28;01mFalse[39;00m)
[1;32m   1119[0m     [38;5;129;01mand[39;00m ax [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m   1120[0m ):
[1;32m   1121[0m     [38;5;28;01mimport[39;00m [38;5;21;01mmpl_toolkits[39;00m  [38;5;66;03m# type: ignore[39;00m

File [0;32m~/.local/lib/python3.8/site-packages/xarray/plot/utils.py:34[0m, in [0;36mimport_matplotlib_pyplot[0;34m()[0m
[1;32m     32[0m [38;5;124;03m"""import pyplot"""[39;00m
[1;32m     33[0m [38;5;66;03m# TODO: This function doesn't do anything (after #6109), remove it?[39;00m
[0;32m---> 34[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m     36[0m [38;5;28;01mreturn[39;00m plt

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

